INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '1');
INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '2');
INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '3');


INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-11-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '2');

INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-11-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '3');


INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Ballet Under The Stars','Fort Canning Park', '2019-11-25', '19:00:00', 'Performing and Visual Arts', 'http://image6.photobiz.com/2492/37_20181009123959_4871467_large.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '3');


INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Ballet Under The Stars','Fort Canning Park', '2019-11-25', '19:00:00', 'Performing and Visual Arts', 'http://image6.photobiz.com/2492/37_20181009123959_4871467_large.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '2');