INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '1');
INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '2');
INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '3');
INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Learning Day 2019','Esplanade', '2019-12-30', '10:00:00', 'Business', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F64535473%2F191617612291%2F1%2Foriginal.20190627-091917?w=800&auto=compress&rect=0%2C4%2C1200%2C600&s=06cb2d3ac9ce416a56d9afd5637fbde5','NUS-ISS is excited to bring back Learning Day for the 5th consecutive year, as part of the nationwide SkillsFuture Festival. Learning Day 2019 inspires to cultivate the next generation of digital talent to realise their aspiration and potential through mastery of future ready skills. \r\n' + '\r\n' +
'Expect engaging and insightful talks coupled with demonstrations for easy understanding by experienced staff, industry partners and students that have come together to curate the programme into 10 distinct tracks. Namely, Artificial Intelligence, Cybersecurity, Data Science, Digital Transformation & Leadership, Digital Agility, Digital Marketing & Design Thinking, Digital Products & Platforms, Smart Systems, Smart Health and StackUp. \r\n' + '\r\n' +
'Go on a memorable learning journey and reach for the stars as you dive deep into these skills to stay relevant in a future Singapore.' , '1');

INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Learning Day 2019','Esplanade', '2019-12-30', '10:00:00', 'Business', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F64535473%2F191617612291%2F1%2Foriginal.20190627-091917?w=800&auto=compress&rect=0%2C4%2C1200%2C600&s=06cb2d3ac9ce416a56d9afd5637fbde5','NUS-ISS is excited to bring back Learning Day for the 5th consecutive year, as part of the nationwide SkillsFuture Festival. Learning Day 2019 inspires to cultivate the next generation of digital talent to realise their aspiration and potential through mastery of future ready skills. \r\n' + '\r\n' +
'Expect engaging and insightful talks coupled with demonstrations for easy understanding by experienced staff, industry partners and students that have come together to curate the programme into 10 distinct tracks. Namely, Artificial Intelligence, Cybersecurity, Data Science, Digital Transformation & Leadership, Digital Agility, Digital Marketing & Design Thinking, Digital Products & Platforms, Smart Systems, Smart Health and StackUp. \r\n' + '\r\n' +
'Go on a memorable learning journey and reach for the stars as you dive deep into these skills to stay relevant in a future Singapore.' , '2');


INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Learning Day 2019','Esplanade', '2019-12-30', '10:00:00', 'Business', 'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F64535473%2F191617612291%2F1%2Foriginal.20190627-091917?w=800&auto=compress&rect=0%2C4%2C1200%2C600&s=06cb2d3ac9ce416a56d9afd5637fbde5','NUS-ISS is excited to bring back Learning Day for the 5th consecutive year, as part of the nationwide SkillsFuture Festival. Learning Day 2019 inspires to cultivate the next generation of digital talent to realise their aspiration and potential through mastery of future ready skills. \r\n' + '\r\n' +
'Expect engaging and insightful talks coupled with demonstrations for easy understanding by experienced staff, industry partners and students that have come together to curate the programme into 10 distinct tracks. Namely, Artificial Intelligence, Cybersecurity, Data Science, Digital Transformation & Leadership, Digital Agility, Digital Marketing & Design Thinking, Digital Products & Platforms, Smart Systems, Smart Health and StackUp. \r\n' + '\r\n' +
'Go on a memorable learning journey and reach for the stars as you dive deep into these skills to stay relevant in a future Singapore.' , '3');

INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '2');

INSERT INTO event (name, venue, _date, _time, category, img_url, description, account_id) VALUES('Mateus Asato Live in Singapore 2019','Scape', '2019-09-25', '19:00:00', 'Performing and Visual Arts', 'https://cdn.citynomads.com/wp-content/uploads/2019/07/10185754/Mateus-2.jpg','Catch Mateus Asato, one of today’s most influential guitarists, live in concert with his band – Yas Nomura (Japan) on bass, and Chow Kiat (Singapore) on drums.' , '3');